import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavbarLayout } from '@/app/(main)/components/NavbarLayout'
import Image from 'next/image';
import bmw from '@/../public/bmw.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section className=''>
      <header className=''>
        <NavbarLayout />
      </header>
      <div className='p-5'>
        {children}
      </div>
    </section>

  )
}

