import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "../providers";
import HeaderAuth from '@/app/(authentication)/components/NavbarAuth';
import Image from 'next/image';
import bmw from '@/../public/bmw.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <section className='mx-auto flex-grow'>
      <HeaderAuth />
      <div className="container flex flex-col items-center justify-center gap-4 py-8 md:py-10">
        <div className="inline-block max-w-lg text-center justify-center z-20">
          {children}
        </div>
      </div>
    </section>


  )
}
