import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "@/app/providers";
import { NavbarLayout } from '@/app/(main)/components/NavbarLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body className="min-h-screen font-sans antialiased">
                <Providers>
                    <main className=''>
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    )
}


